config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  get '/all_bills/:id', to: 'groups#show_all_bills', as: :all_bills
  get '/split_bills/:id', to: 'groups#split_bills', as: :split_bills
  resources :groups do 
    resources :bills
  end

  

  

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base

	has_many :user_groups
	has_many :users, through: :user_groups
	has_many :bills

	# Get no of participants in group
	def get_no_of_users
		users.select(:id).count
	end

	# Get total expnse of group
	def get_total_expense
		bills.pluck(:amount).inject(:+) rescue 0
	end 

	# Get equal share
	def split_total_amt(current_user)
		equal_share = (get_total_expense / get_no_of_users).round(2) rescue 0
		#all_users = self.users - [current_user]
		all_users = self.users
		result_array = find_user_split_amt(all_users, equal_share, current_user)
		return result_array
	end

	# Find split for each user in group
	def find_user_split_amt(all_users, equal_share , current_user)
		result_array = [];
		tmp_array = all_users.map{|user| [user.email, equal_share - user.user_expense(self.id)]}
		p_array = tmp_array.select{|email, v| v > 0 }
		n_array = tmp_array - p_array
		#n_array = tmp_array.select{|email, v| v < 0 }

		p_array.each_with_index do |p_record, p_index|
			n_array.each_with_index do |n_record, n_index|
				if n_record[1].abs > p_record[1]
					puts "#{p_record[0]} will pay to #{n_record[0]} value = #{p_record[1]}"
					result_array = create_result_set(p_record, n_record, current_user, result_array, p_record[1])
					n_value = n_record[1].abs - p_record[1]
					n_array[n_index] = [n_record[0], n_value]
					n_record = [n_record[0], n_value]
					p_array[p_index] = [p_record[0], 0]
					p_record = [p_record[0], 0]
				else
					puts "#{p_record[0]} will pay to #{n_record[0]} value = #{n_record[1].abs}"
					result_array = create_result_set(p_record, n_record, current_user, result_array, n_record[1].abs)
					value = p_record[1] - n_record[1].abs
					p_array[p_index] = [p_record[0], value]
					p_record = [p_record[0], value]
					n_record = [n_record[0], 0]
					n_array[n_index] = [n_record[0], 0]
				end
			end
		end
		return result_array
	end

	def create_result_set(p_record, n_record, current_user, result_array, replace_value)
		if p_record[0] == current_user.email && replace_value > 0
			result_array.push([n_record[0], replace_value, 'pay him'])
		elsif n_record[0] == current_user.email && replace_value > 0
			result_array.push([p_record[0], replace_value, 'owes you'])
		end
		result_array
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :bills


  def self.get_all_users_name(user)
  	all - [user]
  end

  def user_expense(group_id)
    amt = Bill.where(group_id: group_id, user_id: self.id).pluck(:amount)
    amt.present? ? amt.inject(:+) : 0
  end


end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

	before_action :set_group, only:[:new, :create, :show]

	# Add new bill
	def new
		@bill = @group.bills.new
		@users = @group.users.pluck(:email, :id)
	end

	# Add new bill
	def create
		@group.bills.create(bill_params)
		redirect_to :groups, notice: 'Bill created successfully'
	end

	# Show all bills
	def show_all_bills_of_group
		@bills = @group.bills
	end

	# Destroy bill
	def destroy
		if params[:id].present?
			Bill.find(params[:id]).destroy
		end
		redirect_to bills_url, notice: 'Bill was successfully destroyed.'
	end
	

	private
		def set_group
    		@group = Group.find(params[:group_id])
		end

		def bill_params
			params.require(:bill).permit(:name, :location, :amount, :user_id, :payment_date)
		end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	before_action :set_group, only: [:show_all_bills, :split_bills]

	# Show all groups /groups
	def index
		@groups = current_user.groups
	end

	# Initialise new groups 
	def new
		@all_users = User.get_all_users_name(current_user)
		@group = current_user.groups.new
	end

	# Create new group and add members
	def create
		@group = current_user.groups.create(group_params)
		if params[:users].present?
			params[:users].each do |user_id|
				@group.user_groups.create(user_id: user_id)
			end
		end
		redirect_to :groups, notice: 'Group created successfully'
	end

	# Destroy group
	def destroy
		if params[:id].present?
			Group.find(params[:id]).destroy
		end
		redirect_to groups_url, notice: 'Group was successfully destroyed.'
	end

	# Show all group bills
	def show_all_bills
		@bills = @group.bills
	end

	# Split bills and show each share
	def split_bills
		@results = @group.split_total_amt(current_user)
	end

	private 

		def group_params
			params.require(:group).permit(:name, :description)
		end

		def set_group
			@group = Group.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def format_date(date)
		date.strftime("%d/%m/%Y") if date.present?
	end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/bills/new.html.erb
<div class='container'>
	<h1>Add Bill</h1>

	<%= form_for(:bill, url: group_bills_path) do |f|%>

		<div class="fields">
			<%= f.label :name  %>
			<%= f.select :name , options_for_select(['Tea', 'Lunch', 'Dinner']), {}, class: 'form-control'%>
		</div><br>

		<div class="fields">
			<%= f.label :location %>
			<%= f.text_field :location , class: 'form-control'%>
		</div><br>

		<div class="fields">
			<%= f.label :amount %>
			<%= f.number_field :amount, min: 0 ,class: 'form-control', required: true %>
		</div><br>


		<div class="fields">
			<%= f.label :payment_date %>
			<%= f.date_field :payment_date, class: 'form-control', max: Date.today %>
		</div><br>


		<div class="fields">
			<%= f.label :paid_by %>
			<%= f.select :user_id, options_for_select(@users), {}, class: 'form-control', prompt: 'Select' %>
		</div><br>

		<%= f.submit %>
	<% end %>
</div>

app/views/groups/index.html.erb
<div class='container'>
	<h2>Groups</h2>

	<table class="table table-bordered table-striped">
		<tr>
			<th>Sr No</th>	
			<th>Name</th>
			<th>No Of Users</th>
			<th>Total Expense</th>
			<th>Actions</th>
		</tr>
		<% counter = 0%>
		<% @groups.each do |group|%>
			<tr>
				<td><%= counter += 1%></td>
				<td><%= group.name %></td>
				<td><%= group.get_no_of_users %></td>
				<td><%= group.get_total_expense%></td>
				<td>
					<%= link_to 'Details', all_bills_path(group.id),class: 'btn-sm' %>
					<%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn-sm' %>
				</td>
			</tr>
		</a>	
		<% end %>
	</table>

<%= link_to 'New Group', new_group_path, class: 'btn btn-sm btn-primary' %>	

</div>

app/views/groups/new.html.erb
<%= stylesheet_link_tag 'prism','chosen.min'%>
<div class='container'>

	<h2>Create New Group</h2>

	<%= form_for @group do |f|%>

		<div class="fields">
			<%= f.label :name  %>
			<%= f.text_field :name, class: 'form-control', required: true %>
		</div><br>

		<div class="fields">
			<%= f.label :description %>
			<%= f.text_area :description , class: 'form-control'%>
		</div><br>

		<div class="fields">
			<%= f.label :users%>
			<%=select_tag "users", options_from_collection_for_select(@all_users, "id", "email"),  multiple: true, class: 'chosen-select form-control' %>
		</div><br>

		<div class="fields">
			<%= f.submit %>
		</div>

		

	<% end %>

</div>
<%= javascript_include_tag 'chosen.jquery.min', 'prism', 'init'%>

app/views/groups/show_all_bills.html.erb
<div class="container">

  <h2><b><%= @group.name %></b> Bills</h2>
	<table class="table table-bordered table-striped">
		<tr>
			<th>Event</th>
			<th>Location</th>
			<th>Amount</th>
			<th>Paid By</th>
			<th>Payment Date</th>
		</tr>

		<% @bills.each do |bill| %>
			<tr>
				<td><%= bill.name %></td>
				<td><%= bill.location %></td>
				<td><%= bill.amount %></td>
				<td><%= bill.user.email %></td>
				<td><%= format_date(bill.payment_date)%></td>
			</tr>
		<% end %>
	</table>

	

<%= link_to 'Add New Bill', new_group_bill_path(@group.id),class: 'btn btn-primary btn-sm' %>
<%= link_to 'Split Bills', split_bills_path(@group.id), class: 'btn btn-sm btn-primary'%>


</div>

app/views/groups/split_bills.html.erb
<div class="container">

<h2><%= current_user.email %></h2>

	<table class="table table-bordered table-striped">

		<tr>
			<th>Name</th>
			<th>Amount</th>
			<th>Status</th>
		</tr>

		<% @results.each do |email, amt, status| %>

			<tr>
				<td><%= email %></td>
				<td><%= amt %></td>
				<td class="<%= status %>"><%= status %></td>
			</tr>

		<% end %>



	</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/partials/header'%>
<div class="container container-fluid text-center">
	<div class="row content">
		<div class="col-md-2 sidenav">

      <h4>User's List</h4>
    	  <p>ramesh@gmail.com - 123456</p>
	      <p>suresh@gmail.com - 123456</p>
	      <p>abhijeet@gmail.com - 123456</p>
	      <p>aditya@gmail.com - 123456</p>
    	</div>
	    <div class="col-md-10 text-left"> 
			<%= yield %>
		</div>
	</div>
</div>
</body>
</html>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/groups">Billing App</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to(current_user.email) if current_user.present? %>
         <% if user_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
            </li>
        <% else %>
            <li>
              <%= link_to('Login', new_user_session_path)  %>  
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>